INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG2','Title','Hello, world!',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG2','Title','Hello, world!',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3','Title','Heading',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3','Title','Heading',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS4','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS4','Title','Here come the news 1',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS4','Title','Here come the news 1',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS5','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS5','Title','Here come the news 2',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS5','Title','Here come the news 2',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS6','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS6','Title','Here come the news 3',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS6','Title','Here come the news 3',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS7','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS7','Title','Here come the news 4',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS7','Title','Here come the news 4',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS8','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS8','Title','Here come the news 5',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS8','Title','Here come the news 5',NULL,NULL,'it');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS9','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS9','Title','Here come the news 6',NULL,NULL,'en');
INSERT INTO contentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS9','Title','Here come the news 6',NULL,NULL,'it');
