INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG2','Title','Hello, world!',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG2','Title','Hello, world!',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3','Title','Heading',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('CNG3','Title','Heading',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS4','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS4','Title','Here come the news 1',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS4','Title','Here come the news 1',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS5','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS5','Title','Here come the news 2',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS5','Title','Here come the news 2',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS6','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS6','Title','Here come the news 3',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS6','Title','Here come the news 3',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS7','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS7','Title','Here come the news 4',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS7','Title','Here come the news 4',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS8','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS8','Title','Here come the news 5',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS8','Title','Here come the news 5',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS9','Date',NULL,'2012-06-13 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS9','Title','Here come the news 6',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS9','Title','Here come the news 6',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS19','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS19','Title','Ricerca di personale per il ripianamento di P.O. nell''ambito degli Organismi Internazionali in Italia',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS19','Title','Ricerca di personale per il ripianamento di P.O. nell''ambito degli Organismi Internazionali in Italia',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS44','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS44','Title','Punto di situazione sui provvedimenti disposti dal Capo di Stato Maggiore dell''Esercito',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS44','Title','Punto di situazione sui provvedimenti disposti dal Capo di Stato Maggiore dell''Esercito',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS47','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS47','Title','Terminati, alla Cecchignola, i lavori di rifacimento delle infrastrutture per il personale del''Operazione "Strade Sicure"',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS47','Title','Terminati, alla Cecchignola, i lavori di rifacimento delle infrastrutture per il personale del''Operazione "Strade Sicure"',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS13','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS13','Title','Certificazione Unica',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS13','Title','Certificazione Unica',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS49','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS49','Title','Guida ai Soggiorni Militari',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS49','Title','Guida ai Soggiorni Militari',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS52','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS52','Title','Colonie Estive 2019',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS52','Title','Colonie Estive 2019',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS30','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS30','Title','Relazione sui ricongiungimenti familiari e l''avvicendamento ai luoghi originari per il personale dell''Esercito Italiano.',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS30','Title','Relazione sui ricongiungimenti familiari e l''avvicendamento ai luoghi originari per il personale dell''Esercito Italiano.',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS27','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS27','Title','Circolare applicativa sulle istanze di trasferimento dei Sottufficiali per l''anno 2019',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS27','Title','Circolare applicativa sulle istanze di trasferimento dei Sottufficiali per l''anno 2019',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS33','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS33','Title','Concorso VFP1 - 2'' Blocco 2019',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS33','Title','Concorso VFP1 - 2'' Blocco 2019',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS36','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS36','Title','Concorso fotografico "Uno scatto in avanti: Le donne nella Difesa" Fotografia un''idea.',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS36','Title','Concorso fotografico "Uno scatto in avanti: Le donne nella Difesa" Fotografia un''idea.',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS16','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS16','Title','Fondo per l''Efficienza per i Servizi Istituzionali (FESI)',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS16','Title','Fondo per l''Efficienza per i Servizi Istituzionali (FESI)',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS10','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS10','Title','Servizio assistenza fiscale',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS10','Title','Servizio assistenza fiscale',NULL,NULL,'it');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS42','Date',NULL,'2019-03-18 00:00:00',NULL,NULL);
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS42','Title','Prosegue l''impegno della Forza Armata a tutela del benessere del proprio personale.',NULL,NULL,'en');
INSERT INTO workcontentsearch (contentid,attrname,textvalue,datevalue,numvalue,langcode) VALUES ('NWS42','Title','Prosegue l''impegno della Forza Armata a tutela del benessere del proprio personale.',NULL,NULL,'it');
